### PR TITLE
failed to parse expression for the special case

### LINKED ISSUE #32: couldn't parse query around fldcat.
This query work good.
```sql
select sid, sname from student where sname = 'joe';
```

But, on the other side, this next query don't work!

```sql
select tblname, fldname from fldcat where tblname = 'student';
```

### PR DESCRIPTION
**Pull request by cutsea110**
resolves #32 .

expression parser partially parse "true"'s first character 't' and then try field parser, expression parser will failed to parse "tblname" as field.
This PR fix the bug.

### CODE REVIEW

File: src/parser/parser.rs [hunk 1]
```diff
@@ -372,10 +372,12 @@ where
     Input: Stream<Token = char>,
     Input::Error: ParseError<Input::Token, Input::Range, Input::Position>,
 {
-    str_tok()
+    attempt(str_tok())
         .map(|sval| Constant::new_string(sval))
-        .or(i32_tok().map(|ival| Constant::new_i32(ival))) // pick it up as the largest signed integer
-        .or(bool_tok().map(|bval| Constant::new_bool(bval)))
+        .or(attempt(i32_tok()).map(|ival| Constant::new_i32(ival))) // pick it up as the largest signed integer
+        .or(attempt(bool_tok()).map(|bval| Constant::new_bool(bval)))
```
Comment (cutsea110) [inline src/parser/parser.rs:378]: attempt does not consume input when parsing failed.

File: src/parser/parser.rs [hunk 2]
```diff
@@ -754,6 +756,20 @@ mod tests {
             parser.parse("'bob'   "),
             Ok((Expression::Val(Constant::String("bob".to_string())), ""))
         );
+        // If expression parser partially parse "true"'s first character 't' and then try field parser,
+        // expression parser will failed to parse "tblname" as field.
+        // This test is to check this bug.
+        assert_eq!(
+            parser.parse("tblname"),
```
Comment (cutsea110) [inline src/parser/parser.rs:763]: add test for "true" case.

File: src/parser/parser.rs [hunk 3]
```diff
@@ -754,6 +756,20 @@ mod tests {
...
+            Ok((Expression::Fldname("tblname".to_string()), ""))
+        );
+        // If expression parser partially parse "false"'s first character 'f' and then try field parser,
+        // expression parser will failed to parse "fldname" as field.
+        // This test is to check this bug.
+        assert_eq!(
+            parser.parse("fldname"),
```
Comment (cutsea110) [inline src/parser/parser.rs:770]: add test for "false" case.
